name: nightreader
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  audioplayers: ^6.5.1
  wakelock_plus: ^1.4.0
  shared_preferences: ^2.5.3
  provider: ^6.1.2
  flutter_animate: ^4.5.2
  share_plus: ^12.0.1
  screen_brightness: ^2.1.7
  url_launcher: ^6.3.2
  firebase_crashlytics: ^5.0.4
  firebase_core: ^4.2.1
  firebase_remote_config: ^6.1.1
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.3.11
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/sounds/
    - assets/icons/
    - assets/privacy_policy.html

# Flutter Launcher Icons configuration
flutter_launcher_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/app-icon.png"
  image_path_ios_dark_transparent: "assets/images/app-icon-foreground.png"
  image_path_android: "assets/images/app-icon.png"
  adaptive_icon_background: "assets/images/app-icon-background.png"
  adaptive_icon_foreground: "assets/images/app-icon-foreground.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/images/app-icon.png"

# Flutter Native Splash configuration
flutter_native_splash:
  color: "#804eb1"
  color_android: "#804eb1"
  color_dark_android: "#121212"
  color_ios: "#804eb1"
  color_dark_ios: "#121212"
  color_web: "#804eb1"
  color_dark_web: "#121212"
  image: "assets/images/app-icon-foreground.png"
  android_12:
    color: "#804eb1"
    icon_background_color: "#804eb1"
    image: "assets/images/app-icon-foreground.png"
    color_dark: "#121212"
    icon_background_color_dark: "#121212"
    image_dark: "assets/images/app-icon-foreground.png"